using AlphaExchange.Core;
using Microsoft.Data.Sqlite;
using System.Text.Json;
using System.Text.Json.Nodes;

string mode=args[0],folder=Path.GetFullPath(args[1]);
if(mode=="generate")
{
    Directory.CreateDirectory(folder);
    var game=new GameEngine(17026);
    if(game.State.Version!=7) throw new Exception("Fixture must be generated by the actual v1.6.0 core");
    var store=new GameStore(folder); store.Attach(game); store.Save(game);
    for(int hour=0;hour<168;hour++) { game.AdvanceHour(); if(game.State.CompletedHours%24==0) store.Save(game); }
    using var db=new SqliteConnection("Data Source="+store.SavePath); db.Open();
    using var cmd=db.CreateCommand(); cmd.CommandText="SELECT hour,resolution,hash FROM hours WHERE run=$run ORDER BY hour,resolution";
    cmd.Parameters.AddWithValue("$run",game.State.RunId); using var reader=cmd.ExecuteReader();
    var rows=new List<object>(); while(reader.Read()) rows.Add(new {hour=reader.GetInt64(0),resolution=reader.GetInt32(1),hash=reader.GetString(2)});
    File.WriteAllText(Path.Combine(folder,"baseline.json"),JsonSerializer.Serialize(new {version=7,run=game.State.RunId,hour=168,rows},new JsonSerializerOptions {WriteIndented=true}));
    Console.WriteLine($"True v7 fixture: {rows.Count} immutable rows;10000 retail;168 hours");
}
else if(mode=="inspect")
{
    var store=new GameStore(folder); var game=store.Load(out string message) ?? throw new Exception("Native save missing: "+message);
    if(message.Length!=0) throw new Exception("Native save required fallback: "+message);
    var json=JsonNode.Parse(game.Serialize())!;
    if(game.State.Version!=8 || json["World"]!["People"]!.AsArray().Count!=200 || game.State.Retail.Count!=10000 ||
        json["World"]!["Rules"]!["InvestorCapital"]!.GetValue<long>()!=10_000_000 || game.SystemCash()!=game.State.InitialSystemCash)
        throw new Exception("Native migration changed financial scale, population or cash");
    if(game.State.CompletedHours<=168 || !game.HistorySource!.Covers(0,game.State.CompletedHours)) throw new Exception("Native hourly history has gaps or failed to advance");
    Console.WriteLine(JsonSerializer.Serialize(new {game.State.Version,game.State.RunId,game.State.CompletedHours,
        minutes=json["CompletedMinutes"]!.GetValue<long>(),pending=json["PendingClockMinutes"]!.GetValue<int>(),
        people=json["World"]!["People"]!.AsArray().Count,retail=game.State.Retail.Count,cashDifference=game.SystemCash()-game.State.InitialSystemCash}));
}
else throw new ArgumentException("generate or inspect required");
